name: uuid
version: 1.0.0
author: Richard Fussenegger <email@example.com>
description: RFC 4122 compliant UUID generator and parser.
homepage: https://github.com/Fleshgrinder/dart-uuid
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  crypto: '>=0.9.2 <3.0.0'
#  convert: '>=1.0.0 <3.0.0'
  convert: 1.0.0
dev_dependencies:
  test: any
